### ISSUE TITLE
Fixed viewport width?

### ISSUE THREAD

**Issue by bfred-it** [mmoulton/capture#5]
Is there a way to force a site to be rendered at a set width?
I thought this would output an image 320px wide:

```
capture  --viewport-width 320 "http://bradfrost.com/"
```

**Comment by craigfrancies** [comment]
@bfred-it it looks like it's been documented wrong, works with `viewportWidth` rather than `viewport-width`

```
capture  --viewportWidth 320 "http://bradfrost.com/"
```
